version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql123
      MYSQL_ROOT_PASSWORD: mysql123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql